[project]
name = "crash-notifier"
version = "0.1.0"
description = "A Slack/Email notifier for crash reports"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["requests>=2.32.3", "watchdog>=6.0.0"]
